# -*- coding: utf-8 -*- 
"""
Project: Psychophysics_exps
Creator: Miao
Create time: 2020-12-29 21:38
IDE: PyCharm
Introduction:
"""
KEPT_COL_NAMES_STIMU_DF = ["crowdingcons",
                           "winsize",
                           "index_stimuliInfo",
                           "N_disk",
                           "alig_v_angle6_step1_sectors",
                           "alig_v_angle12_step1_sectors",
                           "alig_v_angle6_step6_cont",
                           "alig_v_angle12_step12_cont",
                           "alig_v_angle6_step1_count",
                           "alig_v_angle12_step1_count",
                           "alig_v_angle6_step6_sectors",
                           "alig_v_angle12_step12_sectors",
                           "alig_v_line_step1_cont",
                           "alig_v_line_step1_sectors",
                           "alig_v_angle6_step1_squared_w",
                           "alig_v_angle12_step1_squared_w",
                           "alig_v_angle6_step1",
                           "alig_v_angle12_step1",
                           "alig_v_angle6_step6",
                           "alig_v_angle12_step12"]

KEPT_COL_NAMES = ["crowdingcons",
                  "Display",
                  "N_disk",
                  "participant_N",
                  "response",
                  "sex",
                  "whichBlock",
                  "deviation_score",
                  "index_stimuliInfo",
                  "winsize",
                  "count_number",
                  "positions",
                  "convexHull",
                  "averageE",
                  "avg_spacing",
                  "occupancyArea",
                  "aggregateSurface",
                  "density",
                  "density_itemsperdeg2",
                  "list_index",
                  "alig_v_angle6_step1_sectors",
                  "alig_v_angle12_step1_sectors",
                  "alig_v_angle6_step6_cont",
                  "alig_v_angle12_step12_cont",
                  "alig_v_angle6_step1_count",
                  "alig_v_angle12_step1_count",
                  "alig_v_angle6_step6_sectors",
                  "alig_v_angle12_step12_sectors",
                  "alig_v_line_step1_cont",
                  "alig_v_line_step1_sectors",
                  "alig_v_angle6_step1_squared_w",
                  "alig_v_angle12_step1_squared_w",
                  "alig_v_angle6_step1",
                  "alig_v_angle12_step1",
                  "alig_v_angle6_step6",
                  "alig_v_angle12_step12"]

