# -*- coding: utf-8 -*- 
"""
Project: Psychophysics_exps
Creator: Miao
Create time: 2020-12-29 21:38
IDE: PyCharm
Introduction:
"""
KEPT_COL_NAMES_STIMU_DF = ["crowdingcons",
                           "winsize",
                           "index_stimuliInfo",
                           "N_disk",
                           "list_index",
                           "align_v_size12",
                           "align_v_size11",
                           "align_v_size10",
                           "align_v_size9",
                           "align_v_size8",
                           "align_v_size7",
                           "align_v_size6",
                           "align_v_size5",
                           "align_v_size4",
                           "align_v_size3",
                           "align_v_size2",
                           "align_v_size1"]

KEPT_COL_NAMES_STIMU_DF2 = ["crowdingcons",
                            "winsize",
                            "index_stimuliInfo",
                            "N_disk"]

KEPT_COL_NAMES = ["crowdingcons",
                  "Display",
                  "N_disk",
                  "participant_N",
                  "response",
                  "sex",
                  "whichBlock",
                  "deviation_score",
                  "index_stimuliInfo",
                  "winsize",
                  "count_number",
                  "positions",
                  "convexHull",
                  "averageE",
                  "avg_spacing",
                  "occupancyArea",
                  "aggregateSurface",
                  "density",
                  "density_itemsperdeg2",
                  "list_index",
                  "align_v_size12",
                  "align_v_size11",
                  "align_v_size10",
                  "align_v_size9",
                  "align_v_size8",
                  "align_v_size7",
                  "align_v_size6",
                  "align_v_size5",
                  "align_v_size4",
                  "align_v_size3",
                  "align_v_size2",
                  "align_v_size1"]

KEPT_COL_NAMES2 = ["crowdingcons",
                   "Display",
                   "N_disk",
                   "participant_N",
                   "whichBlock",
                   "deviation_score",
                   "index_stimuliInfo",
                   "winsize",
                   "count_number",
                   "positions",
                   "density_itemsperdeg2",
                   "list_index"]

KEPT_COL_NAMES3 = ["crowdingcons",
                   "Display",
                   "N_disk",
                   "participant_N",
                   "whichBlock",
                   "deviation_score",
                   "index_stimuliInfo",
                   "winsize",
                   "count_number",
                   "positions",
                   "list_index",
                   "count_number1",
                   "count_number2",
                   "count_number3",
                   "count_number4",
                   "count_number5",
                   "count_number6",
                   "count_number7",
                   "count_number8",
                   "count_number9",
                   "count_number10"]

KEPT_COL_NAMES4 = ["crowdingcons",
                   "Display",
                   "N_disk",
                   "deviation_score",
                   "index_stimuliInfo",
                   "winsize",
                   "a_values"]

KEPT_COL_NAMES5 = ["crowdingcons",
                   "Display",
                   "N_disk",
                   "participant_N",
                   "whichBlock",
                   "deviation_score",
                   "index_stimuliInfo",
                   "winsize",
                   "count_number",
                   "positions",
                   "density_itemsperdeg2",
                   "list_index",
                   "a_values"]

KEPT_COL_NAMES_exp1 = ["Crowding",
                       "Display",
                       "Numerosity",
                       "whichBlock",
                       "response",
                       "participant_N",
                       "blockOrder"]

KEEP_COL_Coor = ["crowdingcons",
                 "winsize",
                 "N_disk",
                 "participant_N",
                 "response",
                 "deviation_score",
                 "percent_change",
                 "response",
                 "displayN",
                 "list_index"]
